config/routes.rb
Rails.application.routes.draw do


    resources:questions, except: [:edit, :update, :destroy] do
    resources:answers, except: [:edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
  end

  def index
    @question = Question.find(params[:question_id])
    @related_answer = @question.answers
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id]
    if @answer.save
      redirect_to question_answers_path(@answer.question)
    else

    end
  end

private
  def answer_params
    params.require(:answer).permit(:answer)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @question = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else

    end
  end
  def show
    @question = Question.find(params[:id])
    
  end



private
  def question_params
    params.require(:question).permit(:question)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/index.html.erb
<h1 align="center">Answers</h1>
<h2 class="padding"> Q # " <%= @question.question %> "</h2>
<div class="padding">
  <% @related_answer.each do |answers| %>
  <div>
    <%= answers.answer %>
  </div>
  <% end %>

</div>
<div class="padding">
  <button type="button" name="button">
    <%= link_to "Add New Answer", new_question_answer_path %>
  </button>
  <button type="button" name="button">
    <%= link_to "Home", questions_path %>
  </button>
  <button type="button" name="button">
    <%= link_to "Back", question_path(@question) %>
  </button>
</div>

app/views/answers/new.html.erb
<h1 align="center">add answer to <%= @question.question %></h1>

<div align="center">
  <%= form_for(:answer , :html => {class: "form-horizontal", role: "form"}, url: question_answers_path()) do |f| %>

    <div class="form-group">

    <div class="control-label col-sm-2">

    <%= f.label :answer %>

    </div>

    <div class="col-sm-8">

    <%= f.text_area :answer, class: "form-control", :rows => 10, style: 'width:50%;', placeholder: "Give an answer", autofocus: true %>

    </div>

    </div>

    <div class="form-group">

    <div class="col-sm-offset-2 col-sm-10">

    <%= f.submit "Enter", class: 'btn btn-primary btn-lg' %>

    </div>

    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpeakCode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1 align="center">Questions Listing</h1>
<div class="padding">
  <% @question.each do |question| %>
    <div class="question_div">
      <%= link_to question.question , question_path(question) %>
    </div>

  <% end %>
</div>
<div class="padding">
  <button type="button" name="button">
    <%= link_to "Add new Question", new_question_path %>
  </button>
</div>

app/views/questions/new.html.erb
<h1 align="center">Add New Question</h1>
<div >
  <%= form_for(:question , :html => {class: "form-horizontal", role: "form"}, url: questions_path) do |f| %>

    <div class="form-group">

    <div class="control-label col-sm-2 question_label">

    <%= f.label :question %>

    </div>

    <div class="col-sm-8">

    <%= f.text_area :question, class: "form-control", :rows => 10, style: 'width:50%;', placeholder: "Enter New Question", autofocus: true %>

    </div>

    </div>

    <div class="form-group">

    <div class="col-sm-offset-2 col-sm-10">

    <%= f.submit "Submit", class: 'btn btn-primary btn-lg' %>

    </div>

    </div>

  <% end %>
</div>

app/views/questions/show.html.erb
<h1 class="padding">Question #</h1>
<h2 class="question_show padding"><%= @question.question %></h2>
<div class="padding">
  <button type="button" name="button">
    <%= link_to "view answers", question_answers_path(@question)%>
  </button>
  <button type="button" name="button">
    <%= link_to "back", questions_path%>
  </button>

</div>